# Generated by Django 4.2.7 on 2023-11-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Start', 'Start'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('done', 'Done')], default='Start', max_length=25),
        ),
    ]
