# Generated by Django 4.2.7 on 2023-12-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
